#!/bin/bash

#It's just useful for me script, that installs packages i need

yay -S gnome
yay -S gnome-extra
yay -S ttf-ms-fonts # I like microsoft fonts + I just need it for some apps and documents
yay -S telegram-desktop
yay -S steam
yay -S viber
yay -S sferum # In Russia, classes are held in this thing named Sferum
yay -S gitg
yay -S krita
yay -S chromium # I use firefox? but sometimes i need chromium
yay -S sudo pacman -Syu bash icoutils wget bubblewrap zstd cabextract bc tar openssl gamemode desktop-file-utils curl dbus freetype2 gdk-pixbuf2 ttf-font zenity lsb-release nss xorg-xrandr vulkan-driver vulkan-icd-loader lsof lib32-freetype2 lib32-libgl lib32-gcc-libs lib32-libx11 lib32-libxss lib32-alsa-plugins lib32-libgpg-error lib32-nss lib32-vulkan-driver lib32-vulkan-icd-loader lib32-gamemode lib32-openssl # This long list of packages is dependencies for portproton
yay -S portproton # I like to play games sometimes :)
yay -S vlc
yay -S zoom
